services:
  - type: web
    name: kino_project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run kino_overseer_web.py --server.port=$PORT
    autoDeploy: true
