# render.yaml
services:
  - type: web
    name: kino-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run kino_overseer_web.py --server.port 8501 --server.enableCORS false
