# kino_project_ai/.render.yaml

services:
  - type: web
    name: kino_project_ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run kino_overseer_web.py
    autoDeploy: true

envVars:
  - key: OPENAI_API_KEY
    sync: true
  - key: TELEGRAM_BOT_TOKEN
    sync: true
  - key: TELEGRAM_CHAT_ID
    sync: true
  - key: STREAMLIT_SERVER_PORT
    value: "7860"
