services:
  - type: web
    name: kino-project-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run kino_overseer_web.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: TELEGRAM_CHAT_ID
        fromEnvVar: TELEGRAM_CHAT_ID
      - key: TELEGRAM_BOT_TOKEN
        fromEnvVar: TELEGRAM_BOT_TOKEN
