# kino_project_ai/.render.yaml

services:
  - type: web
    name: kino-project-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run kino_overseer_web.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
